gearvrf/GearVRf-Demos

input-sample/src/org/gearvrf/io/InputActivity.java
Fix necessary after pull request
"Add Layout container to GVRTextView"
has been merged to GVR Framekwork.
Just to keep the same layout of the application.
See https://github.com/Samsung/GearVRf/pull/378
GearVRf-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>
=> Fix GVRTextView to input-sample

gvr-renderableview/.classpath, gvr-renderableview/project.properties
* Framework location is now "../../GearVRf/GVRf/Framework", same as other
samples
Signed-off-by: Veeren Mandalia <veeren.mandalia@gmail.com>
=> gvr-renderableview: add .classpath, update framework location

gvrf_keyboard_sample/src/org/gearvrf/keyboard/main/MainScript.java
Cause: texture not created on the gl thread
=> Fix a crash in VRKeyboard

events-sample/src/org/gearvrf/input/events/EventsActivity.java, events-sample/src/org/gearvrf/input/events/EventsScript.java
With patch https://github.com/Samsung/GearVRf/pull/434, phone keyboard can be used with gaze, without a headset.
=> Event sample update

gvrf_immersivepedia/src/org/gearvrf/immersivepedia/model/TextDinosaurGroup.java
The text background needs to be a Drawable and the sample program relied on GVRActivity.getDrawable to obtain it. This function is new and not in android 19. We changed to code to convert the bitmap resource to a Drawable using another method. We changed the white background to just use a color instead of a texture.
GearVRf-DCO-1.0-Signed-off-by Nola Donato nola.donato@samsung.com
=> gvr-immersivepedia: Fixed crash when displaying dinosaur text

gvr-remote-scripting/gvrremotescript/src/main/assets/photo.js
with the move to AS, the url locations changed.
=> update url in photo.js

gvr-remote-scripting/gvrremotescript/src/main/java/org/gearvrf/sample/remote_scripting/GearVRScriptingManager.java, gvr-remote-scripting/gvrremotescript/src/main/java/org/gearvrf/sample/remote_scripting/SourceUtils.java
A feature request from our artist:  be able to source script files from within a script.
The api is similar to loading a model.  to source a script from the assets/ directory call:
source.script("filename", "language");  // where 'language' is "lua" or "js"
source.scriptFromSD() loads from sdcard
source.scriptFromURL() loads from url.
=> add a way to source other scripts from within a script

gvr-remote-scripting/build.gradle, gvr-remote-scripting/gvrremotescript/build.gradle
fix package name used by gradle.   upgrade to gradle 2.1.0 since
AndroidStudio keeps asking me to do it anyway.
=> fix package name used by gradle.

gvr-accessibility/gvraccessibility/src/main/java/com/samsung/accessibility/main/MainScript.java, gvr-accessibility/gvraccessibility/src/main/java/com/samsung/accessibility/scene/AccessibilityScene.java, gvr-accessibility/gvraccessibility/src/main/java/com/samsung/accessibility/shortcut/ShortcutMenu.java, gvr-accessibility/gvraccessibility/src/main/java/com/samsung/accessibility/shortcut/ShortcutMenuItem.java
The demo used to crash due to an array reference out of bounds. The code to remove menu items did not work reliably so I rewrote it.
GearVRf-DCO-1.0-Signed-off-by: Nola Donato nola.donato@samsung.com
=> Fixed a crashing but in the gvr-accessibility demo

gvr-exposeapi/gvrexposeapi/src/main/java/org/gearvrf/gvrexposeapi/SampleActivity.java
SampleActivity.onInitAppSettings should call the base class function
GearVRf-DCO-1.0-Signed-off-by: NolaDonato nola.donato@samsung.com
=> Fix coding error in gvr-exposeapi

gvr-3dcursor/settings.gradle
Added a line comment to make it easier to locate the IODevices
folder.
=> gvr-3dcursor: fixed the relative path for io_template

gvr-camera2renderscript/gvrcamera2renderscript/src/main/java/org/gearvrf/gvrcamera2renderscript/Camera2RenderscriptActivity.java, gvr-camera2renderscript/gvrcamera2renderscript/src/main/java/org/gearvrf/gvrcamera2renderscript/Camera2RenderscriptManager.java
A temporary fix for exception in gvr-camera2renderscript app happening due to updating SurfaceTexture in non GL thread. Correct fix in a new pull request.
=> Revert to GVRScript for now

gvr-video/app/src/main/java/org/gearvrf/video/VideoActivity.java, gvr-video/app/src/main/java/org/gearvrf/video/VideoMain.java, gvr-video/app/src/main/res/values/strings.xml
Changed GVR-Video app to use GVRVideoSceneObject, earlier it used to create SurfaceTexture by itself and called updateTexImage() on non-GL Thread
=> Use GVRVideoSceneObject for GVR-Video app

gvr-immersivepedia/gvrimmersivepedia/src/main/java/org/gearvrf/immersivepedia/Main.java
--
```
06-07 14:45:01.136 26607 26607 E AndroidRuntime: FATAL EXCEPTION: main
06-07 14:45:01.136 26607 26607 E AndroidRuntime: Process: org.gearvrf.immersivepedia, PID: 26607
06-07 14:45:01.136 26607 26607 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {org.gearvrf.immersivepedia/org.gearvrf.immersivepedia.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.gearvrf.immersivepedia.scene.DinosaurScene.onPause()' on a null object reference
06-07 14:45:01.136 26607 26607 E AndroidRuntime: at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4659)
06-07 14:45:01.136 26607 26607 E AndroidRuntime: at …
```
=> gvr-immersivepedia: fix NPE crash

gvr-video/app/src/main/java/org/gearvrf/video/VideoMain.java
The mTransitionWeight  was large and radiosity shader was ignoring due to condition.
=> Fix for radiosity after switch to IMAX (#210)

gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/Main.java, gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/util/AudioClip.java
This fixes the issue where sound was still playing when exit the gvr-immersivepedia app. The reason was unnecessary plays flag, which prevented further call to soundPool.stop(streamID). Its safe to call again stop/pause on sound pool as, if the stream is not playing (e.g. is stopped or was previously paused), calling this function will have no effect.
=> gvr-immersivepedia: Fix for audio not stopping when exit app

gvr-bullet/app/src/main/.cproject, gvr-bullet/app/src/main/.project, gvr-bullet/app/src/main/jni/Android.mk, gvr-bullet/app/src/main/jni/Application.mk
gvr-bullet app need libbullet.so file to be in libs folder. Added Android.mk file which copy libbullet.so file to libs.
=> Eclipse bullet sample so file copy to lib dir

gvr-simplegallery/app/src/main/java/org/gearvrf/simplegallery/GalleryActivity.java, gvr-simplegallery/app/src/main/java/org/gearvrf/simplegallery/GalleryMain.java
GVRMain causes the app to crash. Reverting it to
GVRScript till it can be fixed.
=> Revert gvr-simplegallery to GVRScript for now

gvr-remote-scripting/app/build.gradle, gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/GearVRScripting.java, gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/GearVRScriptingMain.java, gvr-remote-scripting/app/src/main/project.properties, gvr-remote-scripting/build.gradle, gvr-remote-scripting/settings.gradle
Using the debugwebserver extension in the gvr-remote-scripting
sample instead of telnet based debug server.
depends on https://github.com/Samsung/GearVRf/pull/638
=> Use debugwebserver in  gvr-remote-scripting sample

gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/GearVRScriptingMain.java
```
07-14 08:19:16.010 27172 27172 E AndroidRuntime: FATAL EXCEPTION: main
07-14 08:19:16.010 27172 27172 E AndroidRuntime: Process: org.gearvrf.sample.remote_scripting, PID: 27172
07-14 08:19:16.010 27172 27172 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {org.gearvrf.sample.remote_scripting/org.gearvrf.sample.remote_scripting.GearVRScripting}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.gearvrf.GVRContext.stopDebugServer()' on a null object reference
07-14 08:19:16.010 27172 27172 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5143)
07-14 08:19:16.010 27172 27172 E AndroidRuntime: 	at …
```
=> gvr-remote-scripting: fix a npe

.gitignore, gvr-widgetviewer/app/build.gradle, gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/GVRWidgetViewer.java, gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/ViewerMain.java
1. Added aar to gitignore for ignoring .aar files in gearvf-libs directory
2. gvr-widgetviewer was not working with GVRMain. Switching to GVRScript for now.
3. gvr-widgetviewer needs change in build.gradle as module name for widget plugin has changed
depends on https://github.com/Samsung/GearVRf/pull/726
=> Make gvr-widget-viewer compatible with aar build

gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/loadComponent/LoadComponent.java
If not set first time render result in error and error shader is called
GearVRf-DCO-1.0-Signed-off-by: 
Deepak Rawat deepak.rawat@samsung.com
=> valueFloatTexture must be set when create circle alpha

common.gradle
I probably missed the memo due to travel and other chaos i was handling,
but would this commit be useful?  I'm adding the relative path to
where the framework aar should be given the way we usually clone the
repos.
=> add the framework outputs directory

gvr-keyboard/app/src/main/java/org/gearvrf/keyboard/spinner/SpinnerItem.java
onStep and drawframeListeners on startup; we have not defined that
so you can't assume anything
=> Looks like gvr-keyboard depends on the order of execution of

gvr-x3d-demo/app/src/main/java/org/gearvrf/x3ddemo/X3DparserActivity.java, gvr-x3d-demo/app/src/main/java/org/gearvrf/x3ddemo/X3DparserScript.java
with other GVR Demos.  Also removed references to
GVRAnimation since that is handled in X3Dobject.
GearVRf-DCO-1.0-Signed-off-by: Mitch Williams 
m1.williams@partner.samsung.com
=> Using GVRMain in place of GVRScene to be consistent

gvr-360photo/app/src/main/java/org/gearvrf/gvr360Photo/Minimal360PhotoMain.java, gvr-360video/app/src/main/java/org/gearvrf/gvr360video/Minimal360Video.java
up the resolution on the spheres used in the 360 samples.
we're getting more and more questions about the quality of photos / videos when viewed in these samples.  they all boil down to the default resolution of the GVRSphereSceneObject.  I don't want to up the resolution on that by default because i don't want to accidentally slow down other apps.  But the 360 photo and video samples need the higher resolution, so, we'll up the resolution in the app.  Sometime later (maybe this weekend), i'll add some convenience constructors for GVRSphereSceneObject so the number of lines needed to set this up is back to the original number of lines.
=> up the resolution on the spheres used in the 360 samples.

gvr-eyepicking/app/src/main/java/org/gearvrf/gvreyepicking/ColorShader.java
After the change to support version 100 and 300 shaders the default version became 100. This sample uses 300 and needs to explicitly mention that now. Not sure whether 100 as default in the framework is better than 300 but I'll leave it be.
=> gvr-eyepicking: explicitly set the shader version for the custom shader

common.gradle
alternative backend; by default oculus will be used
=> Add command line option to enable building the demos with an

gvr-solarsystem/app/src/main/java/org/gearvrf/solarsystem/SolarMain.java
This is Roshan's fix from couple of months back.
Previously the sun was centered at the origin (the camera was inside the sphere) so that lead to:
- no sun visible because the back faces are culled
- a draw call no matter where you would look at
=> gvr-solarsystem: fix the sun position

gvr-nonglthreadupdate/app/src/main/java/org/gearvrf/nonglthreadupdate/SampleMain.java
Needs to go in together with https://github.com/Samsung/GearVRf/pull/900
=> gvr-nonglthreadupdate: use the default text size for the gvrconsole

gvr-opacityanigallery/app/src/main/java/org/gearvrf/opacityanigallery/GalleryMain.java, gvr-opacityanigallery/build.gradle, gvr-opacityanigallery/gradle/wrapper/gradle-wrapper.properties
incorrect rendering order
- set the background sphere to BACKGROUND rendering order
- remove per eye spheres for the background
- replace use of deprecated apis
=> gvr-opacityanigallery: fix potential black quads due to

common.gradle
=> Include 64bit binaries only when the custom ARM64 property is defined

common.gradle, gvr-simplesample/build.gradle, gvr-simplesample/gradle/wrapper/gradle-wrapper.properties, old/common.gradle
dependencies so the demos can be built together with the framework
and the backends.
Set buildGvrfAndDemos to true in gradle.properties and then add
the demo module to extra_settings.gradle; e.g.
include ':gvr-simplesample'
project(':gvr-simplesample').projectDir=new File('<insert-your-path-here/GearVRf-Demos/gvr-simplesample/app')
Do note that the "app" directory has to be referenced.
=> Add a buildGvrfAndDemos gradle property. When set it changes the

common.gradle, old/common.gradle
Prerequisite: https://github.com/Samsung/GearVRf/pull/1093
If the ARM64 property is defined the build will produce apk using the 64bit binaries. Daydream is automatically disabled in this case.
=> Oculus Mobile SDK 1.5.0: support 64bit build with the Oculus backend

gvr-camera2renderscript/app/src/main/java/org/gearvrf/gvrcamera2renderscript/Camera2RenderscriptActivity.java, gvr-camera2renderscript/app/src/main/java/org/gearvrf/gvrcamera2renderscript/RenderscriptProcessor.java
Looks like you can tell at runtime whether the yuv-rgb conversion is necessary (it is for all recent phones apparently). I can't find a phone that doesn't need the conversion so can't verify. I probably need a Note4 with Android L. KitKat just doesn't work due to the use of 21 apis. For now using the old and tried method.
---
=> gvr-camera2renderscript: fix crash on S8

gradle.properties, gvr-modelviewer2/app/build.gradle, old/gradle.properties
+ remove unnecessary property from gradle.property
Needed for the 3.2 release
Removing the org.gradle.parallel allows setting it in the global gradle.properties to true. Building in parallel seems to work pretty good nowadays and there is a great speedup when building and installing the demos.
=> gvr-modelviewer2: Fix the build from maven

common.gradle, old/common.gradle
Using findProjects to detect the presence of the framework projects and use them instead of the aars
Goes together with https://github.com/Samsung/GearVRf/pull/1177
=> Remove the buildGvrfAndDemos option

gvr-360video/app/src/main/java/org/gearvrf/gvr360video/Minimal360Video.java
Setting the scale on the sphere tells the renderer what matrix to apply
when rendering that SphereSceneObject.  however, we're not using the
SphereSceneObject, but rather the vertices from the sphere.  So, apply
the scale to the VideoSceneObject instead.
=> Apply the scale to the video, not the sphere.

gvr-accessibility/app/src/main/java/com/samsung/accessibility/scene/AccessibilityScene.java
Again, the merge and squash github did dropped the change from my pull request..
=> gvr-accessibility: Fix for the inverted colors option not working

gvr-blurfilter/app/src/main/res/raw/gaussianblurhorz.fsh, gvr-blurfilter/app/src/main/res/raw/gaussianblurvert.fsh, gvr-video/app/src/main/java/org/gearvrf/video/shaders/RadiosityShader.java, gvr-video/app/src/main/java/org/gearvrf/video/shaders/ScreenShader.java
Different phone models need different extensions for samplerExternalOES:
Adreno-based, GL_OES_EGL_image_external_essl3
Mali-based, GL_OES_EGL_image_external
Instead of 'require' a particular extension in the fragment shader, 'enable' both.
=> Fix EGL_image_external

gvr-video/app/src/main/java/org/gearvrf/video/shaders/RadiosityShader.java, gvr-video/app/src/main/java/org/gearvrf/video/shaders/ScreenShader.java
Different phone models need different extensions for samplerExternalOES:
Adreno-based, GL_OES_EGL_image_external_essl3
Mali-based, GL_OES_EGL_image_external
Instead of 'require' a particular extension in the fragment shader, 'enable' both.
=> Fix all occurrences of GL_OES_EGL_image_external

gvr-cubemap/app/src/main/java/org/gearvrf/cubemap/CubemapMain.java
Fix: reflective sphere was removed by accident
=> gvr-cubemap: reflective sphere is back

gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/Main.java
- the gear controller objects has a picker of its own that would generate pick events that set the app's picker handler state incorrectly
- also remove redundant PickerHandler (which oddly enough wasn't getting gc-ed which I will look into in the future)
---
Depends on https://github.com/Samsung/GearVRf/pull/1557
=> gvr-immersivepedia: fix interference by the gear controller by disabling the gear controller object

gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/videoComponent/VideoComponent.java
fixes #211 
`active` flag is disabled only after media player is released, but it is checked possibly during the release.
=> releasing media player is time consuming.

common.gradle
Replace the archaic way of specifying the backends to use with, e.g.:
```
backend_oculus=false
backend_daydream=false
backend_monoscopic=true
backend=false
```
If none specified defaults to oculus+daydream, as before.
``no_oculus, only_daydream`` are being removed.
=> gradle: rework the way backends are specified

gvr-x3d-demo/app/src/main/java/org/gearvrf/x3ddemo/X3DparserScript.java
Copy the x3d model and associated assets to the assets folder; then can use ``adb shell setprop debug.gearvrf.gvr-x3d-demo <filename>`` to specify which one to load.
Depends on https://github.com/Samsung/GearVRf/pull/1889
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov m.marinov@samsung.com
=> gvr-x3d-demo: add a property to override the x3d model being loaded

build.gradle
google() needs to be before jcenter()
=> Fixes build issue for travis and in general for common.jar

gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorMain.java, gvr-events/app/src/main/java/org/gearvrf/events/EventsActivity.java, gvr-events/app/src/main/java/org/gearvrf/events/EventsMain.java, gvr-events/app/src/main/res/layout/activity_main.xml, gvr-keyboardview/app/src/main/java/org/gearvrf/keyboardview/Main.java, gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/EditorUtils.java, gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/FileBrowserUtils.java, gvr-renderableview/app/src/main/java/org/gearvrf/renderableview/Main.java, gvr-renderableview/app/src/main/java/org/gearvrf/renderableview/MainActivity.java, gvr-renderableview/app/src/main/res/layout/activity_main.xml, gvr-sceneobjects/app/src/main/java/org/gearvrf/sample/sceneobjects/SampleMain.java, gvr-sceneobjects/app/src/main/java/org/gearvrf/sample/sceneobjects/SceneObjectActivity.java, gvr-videoplayer/app/src/main/java/org/gearvrf/videoplayer/component/MessageText.java, gvr-videoplayer/app/src/main/java/org/gearvrf/videoplayer/component/gallery/Gallery.java, gvr-videoplayer/app/src/main/java/org/gearvrf/videoplayer/component/video/backbutton/BackButton.java, gvr-videoplayer/app/src/main/java/org/gearvrf/videoplayer/component/video/control/ControlWidget.java, gvr-videoplayer/app/src/main/java/org/gearvrf/videoplayer/component/video/dialog/PlayNextDialog.java, gvr-videoplayer/app/src/main/java/org/gearvrf/videoplayer/component/video/loading/LoadingAsset.java, gvr-videoplayer/app/src/main/java/org/gearvrf/videoplayer/component/video/title/OverlayTitle.java
Fixes to UI thread deadlock and improvements to test https://github.com/Samsung/GearVRf/pull/1973
GearVRf-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>
=> Fix UI Thread deadlock

gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/shader/CutoutShader.java, gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/shader/MenuImageShader.java, gvr-immersivepedia/app/src/main/res/raw/cutout_vertex.vsh, gvr-immersivepedia/app/src/main/res/raw/menu_image_shader_fragment.vsh, gvr-immersivepedia/app/src/main/res/raw/menu_image_shader_vertex.vsh
Monoscopic, daydream and other backends that do not support multiview do not show the menu quads otherwise
Was hard-coded to multiview; using shader template to have the flag set accordingly.
=> gvr-immersivepedia: fix menu rendering for backends that do not support multiview

gvr-controller/app/src/main/AndroidManifest.xml
enableVrMode is required for Daydream; the app usually doesn't run on Lenovo's device without it
All apps need this update but for now this is it.
=> gvr-controller, daydream: add required manifest attribute
