gearvrf/GearVRf-Demos

input-sample/src/org/gearvrf/io/InputActivity.java, input-sample/src/org/gearvrf/io/InputScript.java
Removed the deprecated GVRTextViewSceneObject from the input-sample and replaced it with GVRTextView.
=> Changed GVRTextViewSceneObject to GVRTextView

input-sample/src/org/gearvrf/io/InputScript.java
The sample now demonstrates using:
* setPosition(),
* setNearDepth() and
* setFarDepth()
=> Updated input-sample to use the new cursor controller APIs.

events-sample/AndroidManifest.xml, gvr-renderableview/AndroidManifest.xml
Added the READ_EXTERNAL_STROAGE permission.
=> Fixed manifest for events-sample and RenderableView

gvr-javascript/assets/script.js, gvr-javascript/src/org/gearvrf/sample/gvrjavascript/ScriptUtils.java, gvr-lua/assets/script.lua, gvr-lua/src/org/gearvrf/sample/gvrlua/ScriptUtils.java, gvr-remote-scripting/src/org/gearvrf/sample/remote_scripting/GearVRScriptingManager.java, gvrf_immersivepedia/src/org/gearvrf/immersivepedia/model/TextDinosaurGroup.java, gvrf_immersivepedia/src/org/gearvrf/immersivepedia/props/Totem.java, gvrf_immersivepedia/src/org/gearvrf/immersivepedia/scene/MenuItem.java, gvrtextviewsample/src/org/gearvrf/gvrtextviewsample/SampleViewManager.java, scene-objects/src/org/gearvrf/sample/sceneobjects/SampleViewManager.java, scene-objects/src/org/gearvrf/sample/sceneobjects/SceneObjectActivity.java, transparency-test/src/org/gearvrf/samples/transparencyTest/TransparencyTestScript.java
This depends on https://github.com/Samsung/GearVRf/pull/440
=> Updates triggered by the GVRTextViewSceneObject improvements

gvr-vuforia/CopyVuforiaFiles.xml
GearVRf-DCO-1.0-Signed-off-by: Teresa Mao
teresa.mao@samsung.com
=> Fixed build issue with gvr-vuforia in Android Studio

gvrf_keyboard_sample/ant.properties
GearVRf-DCO-1.0-Signed-off-by: Teresa Mao
teresa.mao@samsung.com
=> Fixed build issue with gvrf_keyboard_sample: java version 7

gvr-remote-scripting/assets/photo.js, gvr-remote-scripting/assets/trex.js, gvr-remote-scripting/assets/video.js
Adding some simple javascripts as examples.  The photo and video samples were originally developed by @danke-sra, i only had minor modifications in them.
=> Adding some simple javascripts as examples

gvr-remote-scripting/assets/photo.js, gvr-remote-scripting/assets/trex.js, gvr-remote-scripting/assets/video.js
updated urls.  used a different photosphere.  added semicolons to video.js.
=> script tweaks

gvr-remote-scripting/assets/photo.js, gvr-remote-scripting/assets/trex.js, gvr-remote-scripting/assets/video.js, gvr-remote-scripting/res/raw/fragment.fsh, gvr-remote-scripting/res/raw/vertex.vsh, gvr-remote-scripting/src/org/gearvrf/sample/remote_scripting/CustomPostEffectShaderManager.java, gvr-remote-scripting/src/org/gearvrf/sample/remote_scripting/DisplayUtils.java, gvr-remote-scripting/src/org/gearvrf/sample/remote_scripting/GearVRScriptingManager.java
Added a gamma correction post effect shader in case it is needed after the fact at runtime.
Added names to the scene objects in the scripts.
Scaled the photosphere.
=> More tweaks.

gvr-remote-scripting/gvrremotescript/src/main/assets/video.js
url changed with the move to AS.  updating
=> update url in video.js

gvr-remote-scripting/gvrremotescript/src/main/assets/trex.js
with the move to AS the urls changed.  updating
=> update url in trex.js

gvr-remote-scripting/gvrremotescript/src/main/assets/gvr.xml, gvr-remote-scripting/gvrremotescript/src/main/java/org/gearvrf/sample/remote_scripting/EditorUtils.java
=> Fixed picking on the remote scripting sample

gvr-remote-scripting/gvrremotescript/src/main/assets/trex.js
add scene.bindShaders() so the trex shows up correctly
=> add scene.bindShaders()

gvr-remote-scripting/gvrremotescript/src/main/assets/space_trex.js
adding space trex script from SDC demo.
=> adding space trex script

gvr-events/gvrevents/src/main/java/org/gearvrf/events/EventsScript.java, gvr-javascript/app/src/main/java/org/gearvrf/sample/gvrjavascript/GearVRJavascriptScript.java, gvr-remote-scripting/gvrremotescript/src/main/java/org/gearvrf/sample/remote_scripting/CursorUtils.java
=> Change GVRCursorType to GVRControllerType

gvr-cubemap/build.gradle, gvr-cubemap/gradle.properties, gvr-cubemap/gvrcubemap/build.gradle, gvr-cubemap/gvrcubemap/src/main/java/org/gearvrf/cubemap/CubeMapShader.java, gvr-cubemap/gvrcubemap/src/main/java/org/gearvrf/cubemap/CubemapActivity.java, gvr-cubemap/gvrcubemap/src/main/java/org/gearvrf/cubemap/CubemapScript.java, gvr-cubemap/gvrcubemap/src/main/res/raw/phong_cubemap.fsh, gvr-cubemap/gvrcubemap/src/main/res/raw/vertex_cubemap.vsh
- added copies of the missing shaders from gvrf; Nola will have to update with the right version
- added on touch handling so you can just cycle over all available environments
=> Gvrcubemap build fixed

gvr-remote-scripting/gvrremotescript/src/main/AndroidManifest.xml, gvr-remote-scripting/gvrremotescript/src/main/java/org/gearvrf/sample/remote_scripting/GearVRScripting.java, gvr-remote-scripting/gvrremotescript/src/main/java/org/gearvrf/sample/remote_scripting/GearVRScriptingManager.java, gvr-remote-scripting/gvrremotescript/src/main/java/org/gearvrf/sample/remote_scripting/PassthroughUtils.java
=> Add passthrough camera

gvr-remote-scripting/gvrremotescript/src/main/java/org/gearvrf/sample/remote_scripting/FileBrowserUtils.java, gvr-remote-scripting/gvrremotescript/src/main/java/org/gearvrf/sample/remote_scripting/GearVRScriptingManager.java, gvr-remote-scripting/gvrremotescript/src/main/res/drawable-xxxhdpi/circular_progress_bar.xml, gvr-remote-scripting/gvrremotescript/src/main/res/layout/filebrowser.xml
add a model file browser.  will allow you to load a model from the
filesystem from within VR.
=> add a model file browser.

gvr-remote-scripting/gvrremotescript/src/main/java/org/gearvrf/sample/remote_scripting/FileBrowserUtils.java
=> remove redundant copyright

gvr-jassimp/gvrjassimp/src/main/AndroidManifest.xml
Not sure this is the only problem with the sample. I was getting weird compilation errors implying the libraries from the libs folder were not picked up but then the errors suddenly stopped and I can't get them to reappear no matter what.
=> gvrjassimp: package name correction

gvr-camera2renderscript/gvrcamera2renderscript/src/main/java/org/gearvrf/gvrcamera2renderscipt/mono.rs, gvr-camera2renderscript/gvrcamera2renderscript/src/main/project.properties
Had to duplicate mono.rs; could not find a better quick fix.
=> gvr-camera2renderscript: build fix

gvr-complexscene/gvrcomplexscene/src/main/java/org/gearvrf/complexscene/ColorShader.java, gvr-complexscene/gvrcomplexscene/src/main/java/org/gearvrf/complexscene/SampleActivity.java, gvr-complexscene/gvrcomplexscene/src/main/java/org/gearvrf/complexscene/SampleViewManager.java
Reverted back to the version which uses C++ shaders instead of Java shaders
GearVRf-DCO-1.0-Signed-off-by: Nola Donato nola.donato@samsung.com
=> reverted to single light version

gvr-cubemap/gvrcubemap/src/main/java/org/gearvrf/cubemap/CubemapActivity.java
=> gvr_note4.xml -> gvr.xml

gvr-events/build.gradle, gvr-events/gvrevents/src/main/java/org/gearvrf/events/EventsScript.java
Also bumped the gradle version
=> gvr-events: fixed sample to process all motion and key events

gvr-video-staticlib/README.txt
GearVRf-DCO-1.0-Signed-off-by: Jason Kim
jason2.kim@samsung.com
=> update instructions in README.txt

gvr-lua/gvrlua/src/main/java/org/gearvrf/gvrlua/GearVRLua.java
=> fixing gvr-lua

gvr-widgetviewer/gvrwidgetviewer/src/main/java/org/gearvrf/widgetViewer/MyGdxWidget.java
=> fix gvr-widgetviewer

gvr-immersivepedia/gvrimmersivepedia/src/main/java/org/gearvrf/immersivepedia/Main.java, gvr-immersivepedia/gvrimmersivepedia/src/main/java/org/gearvrf/immersivepedia/MainActivity.java
there's a little more work to be done before it can fully switch to
GVRMain.
=> revert this one back to GVRScript

gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorScript.java
1. Avoiding setting position of cursor in GearS2Button and HandCursorButton
when IoDevice is GearVR
2. Changed activeCursors to enabledCursors in LaserCursorButton
=> gvr-3dcursor: Bugfixes for single IoDevice

gvr-immersivepedia/gvrimmersivepedia/src/main/java/org/gearvrf/immersivepedia/Main.java, gvr-immersivepedia/gvrimmersivepedia/src/main/java/org/gearvrf/immersivepedia/MainActivity.java, gvr-immersivepedia/gvrimmersivepedia/src/main/java/org/gearvrf/immersivepedia/model/RotateDinosaurGroup.java, gvr-immersivepedia/gvrimmersivepedia/src/main/java/org/gearvrf/immersivepedia/scene/DinosaurScene.java
Bug fix - stop the audio in onPause() state.
=> Bug fix - ImmersivePedia.

gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorActivity.java, gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorMain.java
=> gvr-3dcursor: Switch to GVRMain

gvr-3dcursor/app/build.gradle, gvr-3dcursor/app/src/main/assets/settings.xml, gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorMain.java, gvr-3dcursor/settings.gradle
Added gearwear as an IoDevice in the app. It can be enabled using
the settings UI or the GearS2Button.
=> gvr-3dcursor: Adding support for gearS2

gvr-video/app/src/main/java/org/gearvrf/video/Button.java, gvr-video/app/src/main/java/org/gearvrf/video/VideoActivity.java, gvr-video/app/src/main/java/org/gearvrf/video/VideoMain.java
Refactored gvr-video app. Below are the changes
1 - Removed unnecessary left and right cinema resources.
2 - Removed unused global root menu.
3 - Made a generic button GVRSceneObject.
4 - Removed unnecessary global variables, etc.
Let me know if anyone have more ideas for improvements.
Thanks,
=> gvr-video app refactor

gvr-polyline/polyline/src/main/AndroidManifest.xml
=> gvr-polyline: add the icon in the manifest to prevent build error

gvr-eyepicking/gvreyepicking/src/main/java/org/gearvrf/gvreyepicking/SampleActivity.java, gvr-eyepicking/gvreyepicking/src/main/java/org/gearvrf/gvreyepicking/SampleMain.java
worker thread doesn't work in all the cases we have
=> gvr-complexscene: revert to GVRScript, adding a shader from a

gvr-complexscene/gvrcomplexscene/src/main/java/org/gearvrf/complexscene/SampleActivity.java, gvr-complexscene/gvrcomplexscene/src/main/java/org/gearvrf/complexscene/SampleMain.java
The commit from yesterday was actually for gvr-eyepicking
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>y
=> gvr-complexscene - revert to using GVRScript for now

gvr-simplesample/simplesample/src/main/java/org/gearvrf/simplesample/SampleActivity.java, gvr-simplesample/simplesample/src/main/java/org/gearvrf/simplesample/SampleMain.java
=> gvr-simplesample: revert to using GVRScript

gvr-360video/gvr360video/src/main/build.xml
=> gvr-360video: set the apk name by including a pregenerated build.xml

README.md
=> Test webhook for jenkins

README.md
=> Test webhook for jenkins again

README.md
Here's what worked for me on OSX 10.11. Hopefully will help others get started faster. Closes #196
=> Instructions for running the demos

gvr-remote-scripting/app/src/main/assets/photo.js, gvr-remote-scripting/app/src/main/assets/space_trex.js, gvr-remote-scripting/app/src/main/assets/trex.js, gvr-remote-scripting/app/src/main/assets/video.js
This fixes the paths broken by the change made to the module name
for each sample.
=> Fix paths for assets referenced by urls.

gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/MainActivity.java
=> gvr-immersivepedia: kill the app process on back key

gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/Main.java, gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/MainActivity.java
=> gvr-immersivepedia crash on pause fix - #219

gvr-jassimp/app/src/main/java/org/gearvrf/gvrjassimp/JassimpModelLoaderMain.java
=> gvr-jassimp: fix the tree asset url

gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/scene/MenuScene.java
=> DinosaurScene show must be called only once

gvr-multilight/app/src/main/java/org/gearvrf/multilight/MultiLightMain.java
=> Use the correct loadModel call

gvr-exposeapi/app/src/main/java/org/gearvrf/gvrexposeapi/SampleActivity.java
=> gvr-exposeapi: fix compilation error

gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/Main.java
Can start processing clicks too early; leads to
```
07-13 10:25:57.514 30074 30074 E AndroidRuntime: FATAL EXCEPTION: main
07-13 10:25:57.514 30074 30074 E AndroidRuntime: Process: com.samsung.android.gvr.sample, PID: 30074
07-13 10:25:57.514 30074 30074 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'org.gearvrf.GVRScene org.gearvrf.GVRContext.getMainScene()' on a null object reference
07-13 10:25:57.514 30074 30074 E AndroidRuntime: 	at org.gearvrf.immersivepedia.focus.FocusableController.clickProcess(FocusableController.java:83)
07-13 10:25:57.514 30074 30074 E AndroidRuntime: 	at org.gearvrf.immersivepedia.Main.onSingleTapConfirmed(Main.java:81)
07-13 10:25:57.514 30074 30074 E AndroidRuntime: 	at …
```
=> gvr-immersivepedia: fix fatal npe

gvr-pickandmove/app/src/main/java/org/gearvrf/pickandmove/PickandmoveMain.java, gvr-pickandmove/build.gradle, gvr-pickandmove/gradle/wrapper/gradle-wrapper.properties
=> gvr-pickandmove: fix the exception

gvr-accessibility/app/src/main/java/com/samsung/accessibility/main/Main.java, gvr-accessibility/app/src/main/java/com/samsung/accessibility/shortcut/ShortcutMenuItem.java, gvr-collision/app/src/main/java/org/gearvrf/gvrcollision/CollisionMain.java, gvr-solarsystem/app/src/main/java/org/gearvrf/solarsystem/SolarMain.java
This includes:
gvr-collision
gvr-accessibility
gvr-solarsystem
=> Fix samples with multiple parents "UnsupportedOperationException"

gvr-nonglthreadupdate/app/src/main/java/org/gearvrf/nonglthreadupdate/SampleActivity.java, gvr-nonglthreadupdate/app/src/main/java/org/gearvrf/nonglthreadupdate/SampleMain.java, gvr-opacityanigallery/app/src/main/java/org/gearvrf/opacityanigallery/GalleryActivity.java, gvr-opacityanigallery/app/src/main/java/org/gearvrf/opacityanigallery/GalleryMain.java
gvr-nonglthreadupdate
gvr-opacityanigallery
The apps crash when using GVRMain.
=> Reverted 2 samples to GVRScript

gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/model/RotateDinosaurGroup.java, gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/model/VideoDinosaurGroup.java, gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/scene/DinosaurScene.java
=> Fixes in immersivepedia 

gvr-keyboard/app/src/main/java/org/gearvrf/keyboard/main/Main.java, gvr-keyboard/app/src/main/java/org/gearvrf/keyboard/speech/SoundWave.java
=> gvr-keyboard: fix adding scene objects

gvr-x3d-demo/app/src/main/java/org/gearvrf/x3ddemo/X3DparserActivity.java
=> gvr-x3d-demo: specify the correct configuration file

gvr-renderableview/app/src/main/java/org/gearvrf/renderableview/Main.java
=> gvr-renderableview: fix compile error

gvr-camera2renderscript/app/src/main/java/org/gearvrf/gvrcamera2renderscript/RenderscriptProcessor.java
=> gvr-camera2renderscript: add model SM-N9208 as one needing

gvr-outline/app/src/main/java/org/gearvrf/gvroutline/OutlineShader.java
It doesn't like gl_FragColor.
GearVRf-DCO-1.0-Signed-off-by: Roshan Chaudhari roshan.c@samsung.com
=> fix shader for gvr-outline sample

gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/EditorUtils.java, gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/FileBrowserUtils.java
=> Fix MotionEvent handling in gvr-remote-scripting

gvr-modelviewer2/app/build.gradle
=> Modelviewer2 gradle changes so it uses the common.gradle file

VRHackathons/gvr-sociobowl/app/build.gradle
=> Fix socio bowl build

common.gradle
=> Add dependency to the backend's aar

gvr-modelviewer2/app/src/main/java/org/gearvrf/modelviewer2/Controller.java
add x3d to list of recognized types
=> add x3d to list of recognized types

gradle.properties, settings.gradle
- disable the parallel gradle build as it doesn't always
produce properly working apks
=> Add the scene-editor to the top-level gradle file

gvr-360video/app/build.gradle, gvr-360video/app/src/main/java/org/gearvrf/gvr360video/Minimal360Video.java, gvr-360video/app/src/main/java/org/gearvrf/gvr360video/Minimal360VideoActivity.java, gvr-360video/build.gradle, gvr-360video/gradle/wrapper/gradle-wrapper.properties
Also the playback is paused and resumed when the activity is paused/resumed.
=> gvr-360video: expand the sample to support playback via the exoplayer

gvr-360photo/app/src/main/java/org/gearvrf/gvr360Photo/Minimal360PhotoMain.java, gvr-360video/app/src/main/java/org/gearvrf/gvr360video/Minimal360Video.java
re-simplify the 360 photo and video app w.r.t. creating a sphere to use.
=> re-simplify the 360 photo and video app.

gvr-3dcursor-simple/app/build.gradle, gvr-3dcursor-simple/app/src/main/assets/settings.xml, gvr-3dcursor-simple/app/src/main/java/org/gearvrf/io/cursorsimple/CursorMain.java, gvr-3dcursor-simple/settings.gradle, gvr-3dcursor/app/build.gradle, gvr-3dcursor/app/src/main/assets/settings.xml, gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorMain.java, gvr-3dcursor/settings.gradle
=> Modified Samples for IO integration

gvr-camera2renderscript/app/src/main/AndroidManifest.xml
=> gvr-camera2renderscript: mark it again as vr_only

gvr-collision/app/build.gradle
=> gvr-collision: correct the app name

gvr-complexscene/app/build.gradle
=> gvr-complexscene: add the missing app name

common.gradle
=> Conditionally include the dependency to Daydream

gvr-outline/app/src/main/java/org/gearvrf/gvroutline/OutlineShader.java
=> gvr-outline: add the expected shader version

gvr-lodtest/app/src/main/assets/gvr.xml
=> gvr-lodtest: add the correct gvr.xml file

common.gradle
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov m.marinov@samsung.com
=> Separate out a Daydream backend

gvr-complexscene/app/build.gradle
=> Fix the apk name for gvr-complexscene

gvr-3dcursor-simple/app/src/main/assets/gvr.xml, gvr-3dcursor/app/src/main/assets/gvr.xml, gvr-accessibility/app/src/main/assets/gvr.xml, gvr-collision/app/src/main/assets/gvr.xml, gvr-controls/app/src/main/assets/gvr.xml, gvr-cubemap/app/src/main/assets/gvr.xml, gvr-events/app/src/main/assets/gvr.xml, gvr-immersivepedia/app/src/main/assets/gvr.xml, gvr-inputsample/app/src/main/assets/gvr.xml, gvr-litshader/app/src/main/assets/gvr.xml, gvr-modelviewer/app/src/main/assets/gvr.xml, gvr-modelviewer2/app/src/main/assets/gvr.xml, gvr-pickandmove/app/src/main/assets/gvr.xml, gvr-remote-scripting/app/src/main/assets/gvr.xml, gvr-video/app/src/main/assets/gvr.xml
depends on https://github.com/Samsung/GearVRf/pull/889
=> Using WearTouchPad in GearVRf-Demos

gvr-solarsystem/app/src/main/java/org/gearvrf/solarsystem/SolarMain.java
=> gvr-solarsystem: correct fix for the sun not being visible

gvr-renderableview/app/src/main/java/org/gearvrf/renderableview/MainActivity.java
=> gvr-renderableview: fix the gvrf website url

gvr-transparencytest/app/src/main/java/org/gearvrf/samples/transparencyTest/TransparencyTest.java, gvr-transparencytest/app/src/main/java/org/gearvrf/samples/transparencyTest/TransparencyTestMain.java
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov m.marinov@samsung.com
=> Minor cleanup of the transparency sample

gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorMain.java
=> 3DCursor sample: Small change to the cursor activation listener

gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorMain.java
GearVRf-DCO-1.0-Signed-off-by: Parth Mehta parth.mehta@samsung.com
=> gvr-3dcursor: Adding a null check for SpaceObject

gvr-camera2renderscript/app/src/main/java/org/gearvrf/gvrcamera2renderscript/RenderscriptProcessor.java, gvr-camera2renderscript/build.gradle, gvr-camera2renderscript/gradle/wrapper/gradle-wrapper.properties
Issue: https://github.com/Samsung/GearVRf/issues/927
=> gvr-camera2renderscript: check for the north america note5

README.md
Updated the README to have discriptions for each of the samples.
=> Updated the README to have discriptions for each of the samples.

build.gradle, common.gradle, gvr-outline/build.gradle, gvr-outline/gradle/wrapper/gradle-wrapper.properties, old/build.gradle, old/common.gradle, old/gvr-jassimp/build.gradle, old/gvr-jassimp/gradle/wrapper/gradle-wrapper.properties
=> Add dependency to JOML as it no longer is included in the framework

common.gradle, gradle.properties, gvr-3dcursor-simple/app/build.gradle, gvr-3dcursor/app/build.gradle, gvr-bullet/app/build.gradle, gvr-modelviewer2/app/build.gradle, gvr-remote-scripting/app/build.gradle, gvr-widgetviewer/app/build.gradle, old/common.gradle, old/gradle.properties
GearVRf-DCO-1.0-Signed-off-by: Parth Mehta <parth.mehta@samsung.com>
=> Use binaries from docs.gearvrf.org

common.gradle
GearVRf-DCO-1.0-Signed-off-by: Parth Mehta <parth.mehta@samsung.com>
=> Remove dependency on docs.gearvrf.org

common.gradle, gvr-3dcursor-simple/app/build.gradle, gvr-3dcursor/app/build.gradle, gvr-bullet/app/build.gradle, gvr-modelviewer2/app/build.gradle, gvr-remote-scripting/app/build.gradle, gvr-simplephysics/app/build.gradle, gvr-widgetviewer/app/build.gradle, old/common.gradle
GearVRf-DCO-1.0-Signed-off-by: Parth Mehta <parth.mehta@samsung.com>
=> Use binaries from mavenCentral

common.gradle
=> Fix for the new useLocalProperties option

gvr-javascript/app/src/main/assets/script_bundle.json
=> gvr-javascript: use the correct script target (@GVRScript to @GVRMain)

gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/Main.java, gvr-immersivepedia/build.gradle, gvr-immersivepedia/gradle/wrapper/gradle-wrapper.properties
scene if showing the dinosaur one.
=> Handle the onBackPress method by returning to the menu

gvr-video/app/build.gradle, gvr-video/app/src/main/AndroidManifest.xml, gvr-video/app/src/main/java/org/gearvrf/video/VideoMain.java, gvr-video/app/src/main/java/org/gearvrf/video/movie/IMAXMovieTheater.java, gvr-video/app/src/main/java/org/gearvrf/video/movie/MovieManager.java, gvr-video/app/src/main/java/org/gearvrf/video/movie/MultiplexMovieTheater.java, gvr-video/app/src/main/java/org/gearvrf/video/overlay/OverlayUI.java, gvr-video/app/src/main/java/org/gearvrf/video/overlay/Seekbar.java
Add ExoPlayer lib for more comprehensive formats support
=> add ExoPlayer lib support

gvr-360video/app/src/main/java/org/gearvrf/gvr360video/Minimal360Video.java, gvr-360video/app/src/main/java/org/gearvrf/gvr360video/Minimal360VideoActivity.java
=> gvr-360video: increase the sphere radius

gvr-sceneobjects/app/src/main/java/org/gearvrf/sample/sceneobjects/SampleMain.java, gvr-sceneobjects/app/src/main/java/org/gearvrf/sample/sceneobjects/SceneObjectActivity.java
* Fixed onPause and onResume.
* Only release the camera onDestroy.
=> Fix the lifecycle for gvr-sceneobjects

README.md
=> Streamline the build instructions

gvr-renderableview/app/src/main/java/org/gearvrf/renderableview/Main.java
=> Remove a releaseNative call

common.gradle, gvr-3dcursor-simple/app/build.gradle, gvr-3dcursor/app/build.gradle, gvr-bullet/app/build.gradle, gvr-modelviewer2/app/build.gradle, gvr-remote-scripting/app/build.gradle, gvr-widgetviewer/app/build.gradle, old/common.gradle
Still waiting for the publishing to complete and verify
=> Start using version 3.1.1

common.gradle
=> Use snapshots for version 3.1.2 from now on

template/GVRFApplication/app/build.gradle
=> Update snapshot version to 3.1.2 in the template

gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorMain.java
=> 3d-cursor: Fix objects to be rotated/scaled on selection

common.gradle, old/common.gradle
- support for release build
- release apks signed with the debug key
=> Cleanup of the build files

common.gradle, old/common.gradle, template/GVRFApplication/app/build.gradle
=> Update the daydream library to v1.30.0

common.gradle, old/common.gradle
=> Modified demos to support the daydream 64 bit backend

gvr-modelviewer2/app/src/main/java/org/gearvrf/modelviewer2/Controller.java
Fixes the NPE in https://github.com/Samsung/GearVRf/issues/1139
=> gvr-modelviewer2: fix NPE when there is no model on the sdcard

gvr-events/app/src/main/java/org/gearvrf/events/EventsActivity.java, gvr-events/app/src/main/res/layout/activity_main.xml, gvr-events/app/src/main/res/layout/list_item.xml
This originated from issue https://github.com/Samsung/GearVRf/issues/1155, "Antialiasing on Views inside GVRSceneObject".
=> gvr-events: use much smaller canvas

common.gradle
Update use of useLocalProperties so it works if you specify the flag in extra_properties.gradle
=> common.gradle: update use of useLocalProperties

common.gradle, old/gvr-exposeapi/app/src/main/java/org/gearvrf/gvrexposeapi/SampleCubeMain.java
+ update to pickup properties from extra_properties.grad
=> gvr-exposeapi, gradle: remove unused import of eye pointee holder

gvr-events/app/src/main/java/org/gearvrf/events/EventsMain.java, gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/EditorUtils.java, gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/FileBrowserUtils.java, old/gvr-inputsample/app/src/main/java/org/gearvrf/io/InputMain.java
Needed for https://github.com/Samsung/GearVRf/pull/1256
---
=> gvr-events, gvr-remote-scripting, gvr-inputsample: changes to work with the updated sensor api

gvr-camera2renderscript/app/src/main/java/org/gearvrf/gvrcamera2renderscript/RenderscriptProcessor.java
adding s8 model numbers to the list of phones which need yuv to rgb conversion.
=> camera2renderscript for vulkan

common.gradle, gvr-3dcursor/app/build.gradle, gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorMain.java
Also, depends on [this PR](https://github.com/Samsung/GearVRf/pull/1368). Works on openGL.  Text panels created by GVRTextView and some of the cubemap textures do not load in vulkan.
=> vulkan: fix gvr-3dcursor

gvr-cubemap/app/src/main/java/org/gearvrf/cubemap/CubemapMain.java
=> gvr-cubemap: additional change to really show the reflective sphere

gvr-renderableview/app/src/main/java/org/gearvrf/renderableview/MainActivity.java, gvr-sceneobjects/app/src/main/java/org/gearvrf/sample/sceneobjects/SampleMain.java, gvr-sceneobjects/app/src/main/java/org/gearvrf/sample/sceneobjects/SceneObjectActivity.java
Fixes keyboardview compatibility: Samsung/GearVRf#1345
- - -
GearVRf-DCO-1.0-Signed-off-by: Dmitriy Vasilev d.vasilev@samsung.com
=> gvr-renderableview, gvr-sceneobjects: use more specific types. Fixes keyboardview.

gvr-particles/app/src/main/java/org/gearvrf/particles/SampleMain.java
based on changes of [this](https://github.com/Samsung/GearVRf/pull/1402) PR.
=> change particle params

gvr-controller/app/src/main/java/org/gearvrf/sample/controller/SampleMain.java
Recommended by @SteveGreatApe in issue https://github.com/Samsung/GearVRf/issues/1339
=> gvr-controller: improve handling of the cursorControllerRemoved event

tutorials/tutorial_2_materials/app/src/main/java/com/example/org/gvrfapplication/MainScene.java, tutorials/tutorial_3_model_animation/app/src/main/java/com/example/org/gvrfapplication/MainScene.java
1. Fix `tutorial2`: mSphere duplicate initialization
2. Remove `Future` functions in `tutorial3`
=> Modifications based on the feedback

common.gradle
Depends on https://github.com/Samsung/GearVRf/pull/1441
=> Use daydream version 1.80

gvr-remote-scripting/app/src/main/assets/addpicking.js, gvr-remote-scripting/app/src/main/assets/photo.js, gvr-remote-scripting/app/src/main/assets/space_trex.js, gvr-remote-scripting/app/src/main/assets/trex.js, gvr-remote-scripting/app/src/main/assets/video.js
Planning to merge on Wednesday
=> gvr-remote-scripting: update the various javascript samples so they work

gvr-simplephysics/app/build.gradle
Will merge in the evening today
=> gvr-simplephysics: support building it from the framework workspace

common.gradle, template/GVRFApplication/app/build.gradle
=> Use the 3.3 framework in the 3.3 demos branch

gvr-controls/app/src/main/java/org/gearvrf/controls/anim/AnimButtonPlay.java, gvr-controls/app/src/main/java/org/gearvrf/controls/anim/AnimCleanButton.java, gvr-controls/app/src/main/java/org/gearvrf/controls/anim/AnimReplaybutton.java, gvr-controls/app/src/main/java/org/gearvrf/controls/focus/ControlSceneObjectBehavior.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/MenuCloseButton.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/MenuHeader.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/MenuHeaderItem.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/RadioButtonSceneObject.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/TouchableButton.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/color/ColorsButton.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/motion/MotionButton.java, gvr-controls/app/src/main/java/org/gearvrf/controls/shaders/ButtonShader.java, gvr-controls/app/src/main/java/org/gearvrf/controls/shaders/ColorSwapShader.java, gvr-controls/app/src/main/java/org/gearvrf/controls/shaders/TileShader.java, gvr-controls/app/src/main/res/raw/buttonshader_fragment.vsh, gvr-controls/app/src/main/res/raw/buttonshader_vertex.vsh, gvr-controls/app/src/main/res/raw/color_swap_shader_fragment.vsh, gvr-controls/app/src/main/res/raw/color_swap_shader_vertex.vsh, gvr-controls/app/src/main/res/raw/tileshader_fragment.vsh, gvr-controls/app/src/main/res/raw/tileshader_vertex.vsh
GVREyePointee has been removed from the API in 4.0
GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com
=> Vulkan: gvr-controls remove EyePointee usages

gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/DiffuseShader.java, gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/DiffuseShader2.java, gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/GlassShader.java, gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/GlassShader2.java, gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/MetalOnlyShader.java, gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/MetalShader2.java, gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/PhongShader.java, gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/PhongShader2.java, gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/PhongShader3.java, gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/ReflectionShader.java, gvr-widgetviewer/app/src/main/java/org/gearvrf/widgetViewer/ViewerMain.java
=> Fixed widgetviewer for vulkan

gvr-controls/app/src/main/java/org/gearvrf/controls/anim/AnimButtonPlay.java, gvr-controls/app/src/main/java/org/gearvrf/controls/anim/AnimCleanButton.java, gvr-controls/app/src/main/java/org/gearvrf/controls/anim/AnimReplaybutton.java, gvr-controls/app/src/main/java/org/gearvrf/controls/focus/ControlSceneObjectBehavior.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/MenuCloseButton.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/MenuHeader.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/MenuHeaderItem.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/RadioButtonSceneObject.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/TouchableButton.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/color/ColorsButton.java, gvr-controls/app/src/main/java/org/gearvrf/controls/menu/motion/MotionButton.java, gvr-events/app/src/main/java/org/gearvrf/events/EventsMain.java
GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com
=> Vulkan: gvr-events: get event hit point properly

gvr-keyboardview/app/src/main/res/layout/main_form.xml, gvr-keyboardview/app/src/main/res/values/colors.xml
alignment_marker_color is a color defined by daydream so it may or
may not be present
=> gvr-keyboardview: fix the build

gvr-controller/app/src/main/java/org/gearvrf/sample/controller/SampleMain.java
Cursor did not appear when using Gaze controller
GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com
=> Fix bug in gvr-controller demo with gaze

gvr-accessibility/app/src/main/java/com/samsung/accessibility/scene/SceneItem.java, gvr-javascript/app/src/main/assets/gvr.xml, gvr-javascript/app/src/main/assets/text.js, gvr-javascript/app/src/main/java/org/gearvrf/sample/gvrjavascript/CustomShaderManager.java, gvr-javascript/app/src/main/res/raw/fragment.fsh, gvr-javascript/app/src/main/res/raw/vertex.vsh
=> Fixing gvr-Javascript

gvr-outline/app/src/main/java/org/gearvrf/gvroutline/OutlineShader.java
Depends on #PR1550.
Fixes issue on Mihail's phone.
=> Adding precision to work on s7

gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/CursorUtils.java, gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/EditorUtils.java, gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/FileBrowserUtils.java
broken functionality will be fixed at a later date
=> gvr-remote-scripting: comment out the bad setSensor calls

gvr-javascript/app/src/main/assets/script.js
Will be properly addressed in the near future
=> gvr-javascript: comment out setSensor call that needs replacing

gvr-javascript/app/src/main/assets/script.js, gvr-modelviewer2/app/build.gradle, gvr-widgetviewer/app/build.gradle
1. Fix the gvr-javascript demo (attach sensor in script)
2. Fix gradle files for gvr-modelviewer2, gvr-widgetviewer to properly build the widgetplugin
GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com
=> Fix gvr-javascript, fix widget builds

VRHackathons/gvr-pokemon/app/build.gradle, common.gradle, template/GVRFApplication/app/build.gradle, tutorials/tutorial_1_simple_app/app/build.gradle, tutorials/tutorial_2_materials/app/build.gradle, tutorials/tutorial_3_model_animation/app/build.gradle, tutorials/tutorial_4_animation/app/build.gradle, tutorials/tutorial_5_controller/app/build.gradle, tutorials/tutorial_6_vr_video/app/build.gradle
GSON already has version 2.8.2
=> gson version 2.8.2

README.md
GitHub has problems parsing `###gvr-` - it should be `### gvr-`.
=> README headings

VRHackathons/bondage/app/build.gradle, VRHackathons/gvr-VRGallery/gvr360photo/build.gradle, VRHackathons/gvr-pokemon/app/build.gradle, VRHackathons/gvr-sociobowl/app/build.gradle, VRHackathons/oVeREater/app/build.gradle, build.gradle, common.gradle, gradle/wrapper/gradle-wrapper.properties, gvr-controller/app/build.gradle, template/GVRFApplication/app/build.gradle, tutorials/tutorial_1_simple_app/app/build.gradle, tutorials/tutorial_2_materials/app/build.gradle, tutorials/tutorial_3_model_animation/app/build.gradle, tutorials/tutorial_4_animation/app/build.gradle, tutorials/tutorial_5_controller/app/build.gradle, tutorials/tutorial_6_vr_video/app/build.gradle
Android gradle build tools plugin version 3.0.1 - requires minimum build tools 26.0.0
=> gradle version

disabled-gvr-video/build.gradle, gvr-360video/app/build.gradle, gvr-360video/app/src/main/java/org/gearvrf/gvr360video/Minimal360Video.java, gvr-360video/app/src/main/java/org/gearvrf/gvr360video/Minimal360VideoActivity.java
ExoPlayer is now version 2.6.0
=> ExoPlayer 2.6.0

build.gradle, common.gradle, gradle/wrapper/gradle-wrapper.properties
Depends on https://github.com/Samsung/GearVRf/pull/1701
=> gradle: move demos to android plugin 3.0.1

common.gradle, gvr-cardboard-audio/app/build.gradle, template/GVRFApplication/app/build.gradle, tutorials/tutorial_1_simple_app/app/build.gradle, tutorials/tutorial_2_materials/app/build.gradle, tutorials/tutorial_3_model_animation/app/build.gradle, tutorials/tutorial_4_animation/app/build.gradle, tutorials/tutorial_5_controller/app/build.gradle, tutorials/tutorial_6_vr_video/app/build.gradle
=> daydream 1.120.0

gvr-complexscene/app/src/main/AndroidManifest.xml, gvr-simplephysics/app/src/main/AndroidManifest.xml
=> Fix couple of app's package names

gvr-simplephysics/app/src/main/java/org/gearvrf/simplephysics/entity/Countdown.java, gvr-simplephysics/app/src/main/java/org/gearvrf/simplephysics/main/MainActivity.java, gvr-simplephysics/app/src/main/java/org/gearvrf/simplephysics/main/MainHelper.java, gvr-simplephysics/app/src/main/java/org/gearvrf/simplephysics/main/MainScript.java, gvr-simplephysics/app/src/main/java/org/gearvrf/simplephysics/shader/ColorShader.java, gvr-simplephysics/app/src/main/java/org/gearvrf/simplephysics/util/MathUtils.java, gvr-simplephysics/app/src/main/java/org/gearvrf/simplephysics/util/VRTouchPadGestureDetector.java
=> gvr-simplephysics: update package name in the rest of the app

common.gradle
=> gradle: add abiFilter so we can use the android profiler

gvr-x3d-demo/app/build.gradle
Requires: https://github.com/Samsung/GearVRf/pull/1724
---
=> gvr-x3d-demo: use the x3d extension

common.gradle
=> gradle: backend tweaks

gvr-cardboard-audio/app/build.gradle, gvr-cardboard-audio/app/src/main/java/org/gearvrf/sample/gvrcardboardaudio/SpatialAudioActivity.java
* Change the demo to use ResonanceAudio extension.
See: https://github.com/Samsung/GearVRf/pull/1692
GearVRf-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>
GearVRf-DCO-1.0-Signed-off-by: Cristiano Bozzetto <c.bozzetto@samsung.com>
=> Change cardboard-audio demo to use resonance audio extension

template/GVRFApplication/app/build.gradle, template/GVRFApplication/build.gradle, template/GVRFApplication/gradle/wrapper/gradle-wrapper.properties
=> Fix template build

gvr-keyboardview/app/src/main/java/org/gearvrf/keyboardview/Main.java
* Update IViewEvents#onStartRendering() event
Depends on https://github.com/Samsung/GearVRf/pull/1769
GearVRf-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>
=> Update IViewEvents usage

gvr-accessibility/app/src/main/java/com/samsung/accessibility/main/Main.java, gvr-accessibility/app/src/main/java/com/samsung/accessibility/main/MainActivity.java, gvr-controller/app/src/main/java/org/gearvrf/sample/controller/SampleMain.java, gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/Main.java, gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/MainActivity.java, gvr-keyboardview/app/src/main/java/org/gearvrf/keyboardview/Main.java, gvr-simplephysics/app/src/main/java/org/gearvrf/simplephysics/main/MainActivity.java, gvr-simplephysics/app/src/main/java/org/gearvrf/simplephysics/main/MainScript.java
immersivepedia: remove unused code
Depends on https://github.com/Samsung/GearVRf/pull/1811
=> simplephysics: use the new onSwipe event

common.gradle
Requires https://github.com/Samsung/GearVRf/pull/1824
=> build: use shared std library

common.gradle, template/GVRFApplication/app/build.gradle
Related to https://github.com/Samsung/GearVRf/pull/1840
=> daydream: switch to v1.130.0

gvr-accessibility/app/src/main/java/com/samsung/accessibility/shortcut/ShortcutMenuItem.java, gvr-accessibility/app/src/main/res/raw/scene_shader_fragment.vsh
Fixes shader issue and overlapped icons. It should remove the older icon from scene.
Depends on PR 1870
GearVRF DCO signed off by: Abhijit Jagdale a.jagdale@samsung.com
=> Fixing demo for vulkan

gvr-camera2renderscript/app/build.gradle, gvr-controls/app/build.gradle, gvr-immersivepedia/app/build.gradle, gvr-keyboard/app/build.gradle
The automated build started failing.
=> gradle, maint_v3.x: fix obscure appt error

gvr-x3d-demo/app/build.gradle
=> gradle, gvr-x3d-demo: fix build warning

gvr-events/app/src/main/java/org/gearvrf/events/EventsActivity.java
Add a listener in gvr-events demo to test the hover support which is being proposed in GVRf (see https://github.com/Samsung/GearVRf/pull/1912).
=> Add a listener for hover event

gvr-blurfilter/app/src/main/java/org/gearvrf/blurfilter/TestMain.java, gvr-blurfilter/app/src/main/java/org/gearvrf/blurfilter/VertBlurShader.java, gvr-blurfilter/app/src/main/res/raw/gaussianblurhorz.fsh, gvr-blurfilter/app/src/main/res/raw/gaussianblurvert.fsh
2 postEffects work with PR 1929 
GearVRF DCO signed off by: Abhijit Jagdale a.jagdale@samsung.com
=> Cleanup of gvr-blurfiter demo

gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorActivity.java, gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorMain.java, gvr-accessibility/app/src/main/java/com/samsung/accessibility/scene/AccessibilityScene.java, gvr-accessibility/app/src/main/java/com/samsung/accessibility/shortcut/ShortcutMenuItem.java, gvr-events/app/src/main/java/org/gearvrf/events/EventsActivity.java, gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/scene/MenuScene.java, gvr-javascript/app/src/main/assets/script_bundle.json, gvr-modelviewer2/app/src/main/java/org/gearvrf/modelviewer2/ModelViewer2Activity.java, gvr-renderableview/app/src/main/java/org/gearvrf/renderableview/MainActivity.java, gvr-sceneobjects/app/src/main/java/org/gearvrf/sample/sceneobjects/SampleMain.java, gvr-sceneobjects/app/src/main/java/org/gearvrf/sample/sceneobjects/SceneObjectActivity.java
gvr-events modified to use GVRApplication directly and to serve as an example.
=> GVRApplication-related changes

gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/EditorUtils.java, gvr-remote-scripting/app/src/main/java/org/gearvrf/sample/remote_scripting/FileBrowserUtils.java
=> gvr-remote-scripting: fix post-gvrapplication compilation errors

template/GVRFApplication/app/build.gradle
Just ignore the libraries that are not necessary.
GearVRf-DCO-1.0-Signed-off-by: Afonso Costa <afonso.j@samsung.com>
=> Fix the template application's build

build.gradle, gradle/wrapper/gradle-wrapper.properties
Depends on https://github.com/Samsung/GearVRf/pull/1979
=> Upgrade to Android gradle plugin v3.1.0

common.gradle, gvr-360video/app/build.gradle, gvr-3dcursor-simple/app/build.gradle, gvr-3dcursor/app/build.gradle, gvr-arcore/app/build.gradle, gvr-bullet/app/build.gradle, gvr-camera2renderscript/app/build.gradle, gvr-cardboard-audio/app/build.gradle, gvr-controls/app/build.gradle, gvr-immersivepedia/app/build.gradle, gvr-javascript/app/build.gradle, gvr-keyboard/app/build.gradle, gvr-modelviewer2/app/build.gradle, gvr-particles/app/build.gradle, gvr-physicsload/app/build.gradle, gvr-ragdoll/app/build.gradle, gvr-remote-scripting/app/build.gradle, gvr-simplephysics/app/build.gradle, gvr-videoplayer/app/build.gradle, gvr-vuforia/app/build.gradle, gvr-widgetlib-viewer/app/build.gradle, gvr-widgetviewer/app/build.gradle, gvr-x3d-demo/app/build.gradle
=> gradle:fix deprecation warnings

gvr-widgetlib-viewer/app/build.gradle
=> gvr-widgetlib-viewer: fix widgetLib reference

gvr-videoplayer/app/build.gradle
=> gvr-videplayer: build fix due to exoplayer disappearing from jcenter
